<a href="https://colab.research.google.com/github/sonupp13/Data-analysis/blob/main/Pandas%20module/pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv')
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df1.dropna(inplace=True)

In [ ]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
df2=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv')

In [ ]:
df2.dropna(axis=1) #To remove column

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

In [ ]:
df2=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv')

In [ ]:
#Fill null values
df2.fillna("Sachin")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Sachin,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Sachin,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Sachin,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Sachin,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,Sachin,1,2,W./C. 6607,23.4500,Sachin,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Sachin,Q

In [ ]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df2.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0
SibSp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282,113803,373450,330877,17463,349909,347742,237736,...,349257,7552,C.A./SOTON 34068,SOTON/OQ 392076,382652,211536,112053,W./C. 6607,111369,370376
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75
Cabin,NaN,C85,NaN,C123,NaN,NaN,E46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B42,NaN,C148,NaN
Embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q

The groupby() function divides the DataFrame into groups based on unique values in the specified column—in this case, 'Survived'. It creates a DataFrameGroupBy object where each group is identified by its unique 'Survived' value (e.g., 0 and 1, or any other unique values present in the 'Survived' column).

In [ ]:
g = df2.groupby('Sex') #divides the DataFrame into groups based on unique values in the specified column

In [ ]:
g

In [ ]:
print(list(df2.groupby('Sex')))

[('female',      PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
880          881         1       2
882          883         0       3
885          886         0       3
887          888         1       1
888          889         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
880      1            230433  26.0000   NaN        S
882      0              7552  10.5167   NaN        S
885      5            382652  29.1250   NaN        Q
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S

[314 rows x 12 columns]), ('male',      PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    22.0      1      0         A/5 21171   7.2500   NaN        S
4    35.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    54.0      0      0             17463  51.8625   E46        S
7     2.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  27.0      0      0            211536  13.0000   NaN        S
889  26.0      0      0            111369  30.0000  C148        C
890  32.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns])]

After using groupby(), you can perform various operations on these grouped subsets. For instance, you might apply aggregation functions, transformations, or filter data within each group. Here's an example of what you might do after grouping:

In [ ]:
g.sum()

<ipython-input-20-8ef9a38d21e2>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  g.sum()

        PassengerId  Survived  Pclass       Age  SibSp  Parch        Fare
Sex
female       135343       233     678   7286.00    218    204  13966.6628
male         262043       109    1379  13919.17    248    136  14727.2865

In [ ]:
g.mean()

<ipython-input-21-c79523bc0c66>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  g.mean()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893

In [ ]:
g.min()

<ipython-input-22-8e0ddbc75b7d>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.min is deprecated. In a future version, a TypeError will be raised. Before calling .min, select only columns which should be valid for the function.
  g.min()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare
Sex,,,,,,,,,
female,2,0,1,"Abbott, Mrs. Stanton (Rosa Hunt)",0.75,0,0,110152,6.75
male,1,0,1,"Abbing, Mr. Anthony",0.42,0,0,110413,0.00

In [ ]:
p = df2.groupby('Pclass')

In [ ]:
p

In [ ]:
p.sum()

<ipython-input-26-53f9312271b0>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  p.sum()

        PassengerId  Survived      Age  SibSp  Parch        Fare
Pclass
1             99705       136  7111.42     90     77  18177.4125
2             82056        87  5168.83     74     70   3801.8417
3            215625       119  8924.92    302    193   6714.6951

In [ ]:
p.mean()

<ipython-input-31-a3462fc9eca1>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  p.mean()

        PassengerId  Survived        Age     SibSp     Parch       Fare
Pclass
1        461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
2        445.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3        439.154786  0.242363  25.140620  0.615071  0.393075  13.675550

In [ ]:
p.median()

<ipython-input-32-1b9c5f4637b9>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  p.median()

        PassengerId  Survived   Age  SibSp  Parch     Fare
Pclass
1             472.0       1.0  37.0    0.0    0.0  60.2875
2             435.5       0.0  29.0    0.0    0.0  14.2500
3             432.0       0.0  24.0    0.0    0.0   8.0500

In [ ]:
p.max()

<ipython-input-33-46fc1347d3fa>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  p.max()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare
Pclass,,,,,,,,,
1,890,1,"Young, Miss. Marie Grice",male,80.0,3,4,WE/P 5735,512.3292
2,887,1,"del Carlo, Mr. Sebastiano",male,70.0,3,3,W/C 14208,73.5000
3,891,1,"van Melkebeke, Mr. Philemon",male,74.0,8,6,W./C. 6609,69.5500

In [ ]:
p.max()['Fare']

<ipython-input-34-b436c9c2a3f9>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  p.max()['Fare']

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [ ]:
p.max().T

<ipython-input-35-71be9d08aab9>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  p.max().T

Pclass,1,2,3
PassengerId,890,887,891
Survived,1,1,1
Name,"Young, Miss. Marie Grice","del Carlo, Mr. Sebastiano","van Melkebeke, Mr. Philemon"
Sex,male,male,male
Age,80.0,70.0,74.0
SibSp,3,3,8
Parch,4,3,6
Ticket,WE/P 5735,W/C 14208,W./C. 6609
Fare,512.3292,73.5,69.55

In [ ]:
p.max().transpose

<ipython-input-16-d63b3af37704>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  p.max().transpose

<bound method DataFrame.transpose of         PassengerId  Survived                         Name   Sex   Age  SibSp  \
Pclass
1               890         1     Young, Miss. Marie Grice  male  80.0      3
2               887         1    del Carlo, Mr. Sebastiano  male  70.0      3
3               891         1  van Melkebeke, Mr. Philemon  male  74.0      8

        Parch      Ticket      Fare
Pclass
1           4   WE/P 5735  512.3292
2           3   W/C 14208   73.5000
3           6  W./C. 6609   69.5500  >